### ISSUE TITLE
Hypixel Addons

### ISSUE THREAD

**Issue by NopoTheGamer** [kr45732/Hypixel-Addons#3]
A quality of dead mod for Hypixel with features ranging from statistic checking, guild join helpers, todo lists, and much more!

Installation
Download the latest release of the mod.
Put the JAR into your mod folder.
Set the Hypixel API key with /hpa:setkey <key> in-game. You can get your Hypixel API key by running /api new.
Features
A guild chat command responder
Send a message when a player joins your guild
Send a message when a player leaves your guild
Automatically retrieve data about a player when they request to join your guild
Sort the mystery box GUI based on stars or rarity
A todo list GUI to keep track of any tasks you want to complete
Customize the sidebar to remove the red numbers, change location, change the background, and much more
A guild MOTD editor which vastly simplifies the process of editing your guild's MOTD
All the commands below and much more to be added soon!
Commands
/hpa:setkey <key> - Set your Hypixel API key for the mod
/hpa - Edit the settings for the mod
/hpa:help - Get a list of all the commands for the mod
/hpa:slayer [player] [profile] - Get a player's slayer statistics
/hpa:skills [player] [profile] - Get a player's skills statistics
/hpa:hotm [player] [profile] - Get a player's heart of the mountain statistics
/hpa:dungeons [player] [profile] - Get a player's dungeons statistics
/hpa:essence information <item> - Get the amount of essence to upgrade an item for each level
/hpa:essence player [player] [profile] - Get a player's essence amounts and essence shop upgrades
/hpa:partyfinder [player] [profile] - A party finder helper that shows a player's dungeon stats
/hpa:guild [player] - Find what guild a player is in
/hpa:motd - A guild MOTD editor to make it easier to modify your guild's MOTD
/hpa:auctions [player] - Get a player's unclaimed auctions on all profiles
/hpa:bazaar <item> - Get bazaar prices of an item
/hpa:bits <item> - Get the bits cost of an item from the bits shop
/hpa:bank [player] [profile] - Get a player's bank and purse coins
/hpa:weight [player] [profile] - Get a player's slayer, skills, dungeons, and total weight
/hpa:harp [player] [profile] - Get a player's harp statistics
/hpa:cakes [player] [profile] - Get a player's active and inactive cake buffs
/hpa:skyblock [player] [profile] - Get a summary of a player's SkyBlock statistics
/hpa:hypixel [player] - Get Hypixel information about a player
/hpa:bedwars [player] - Get a player's Bedwars statistics
/hpa:skywars [player] - Get a player's Skywars statistics
/hpa:arcade [player] - Get a player's Arcade statistics
/hpa:arena [player] - Get a player's Arena statistics
/hpa:duels [player] - Get a player's duels statistics
/hpa:murder_mystery [player] - Get a player's murder mystery statistics
/hpa:build_battle [player] - Get a player's build battle statistics
/hpa:todo - Open the todo list GUI
<> = required arguments; [] = optional arguments. Some commands can have aliases.

**Comment by TymanWasTaken** [comment]
+1

**Comment by TymanWasTaken** [comment]
![Screenshot_20211018-203449](https://user-images.githubusercontent.com/32660892/137839601-f2a38300-5e7e-4801-bf03-843be49e07dd.png)
No I wouldn't github

**Comment by NopoTheGamer** [comment]
> ![Screenshot_20211018-203449](https://user-images.githubusercontent.com/32660892/137839601-f2a38300-5e7e-4801-bf03-843be49e07dd.png) No I wouldn't github

![image](https://user-images.githubusercontent.com/40329022/137839694-548a40bf-7aec-45de-82af-30fe9fce1879.png)
